version: 1
from: "infracamp/kickstart-flavor-gaia:testing"

command:
  build:
    - "sudo scripts/install.sh"
    - "composer update"

  init:
    - "sudo service influxdb start"

  test:
    - "vendor/bin/phpunit"

  init:
    - "sudo service influxdb start"

