version: "3"
services:
  influxdb:
    image: influxdb:1.8
    networks:
      - rudl-metrics
    environment:
      - "INFLUXDB_DB=rudl"
      - "INFLUXDB_HTTP_AUTH_ENABLED=true"
      - "INFLUXDB_ADMIN_USER=admin"
      - "INFLUXDB_ADMIN_PASSWORD=test123"


networks:
  rudl-metrics:
    external: true
