version: 1
from: "infracamp/kickstart-flavor-gaia:testing"

config_file:
  template: "config.php.dist"
  target: "config.php"

command:
  build:
    - "sudo scripts/install.sh"
    - "composer update"


  init:
  - "sudo mkdir -p /data && sudo chown -R influxdb /data"
  - "sudo service influxdb start || true"
    # Bug with influxdb - starts anyway.

  run:
    - "php -f bin/udp-syslog-server.php"

  test:
    - "phpunit"

