version: "3"
services:
  influxdb:
    image: influxdb:1.8
    networks:
      - rudl-metrics
    environment:
      - "INFLUXDB_DB=rudl"
      - "INFLUXDB_HTTP_AUTH_ENABLED=true"
      - "INFLUXDB_ADMIN_USER=admin"
      - "INFLUXDB_ADMIN_PASSWORD=rudl58271"

  mongodb:
    image: mongo:4
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=root"
      - "MONGO_INITDB_ROOT_PASSWORD=example"
    networks:
      - rudl-metrics


networks:
  rudl-metrics:
    external: true
