version: 1
from: "infracamp/kickstart-flavor-gaia:testing"

config_file:
  template: "config.php.dist"
  target: "config.php"

command:
  build:
    - "sudo scripts/install.sh"
    - "composer update"

  init:
  #- "sudo mkdir -p /data && sudo chown -R influxdb /data"
  #- "sudo service influxdb start || true"
  - "sudo chmod 755 /run/secrets/rudl_ssh_private_key || true"
    # Bug with influxdb - starts anyway.

  run:
    - "curl http://localhost/v1/hooks/repo || true"

    - "/opt/bin/runall.sh"

  test:
    - "phpunit"


  test_doc_push:
    - curl -X POST --data '{"@tmid":"abc2","@system":"def","@ts":123456789000,"desc":"sys1"}' http://localhost/v1/push/doc/default
